PACKAGE_NAME="kwebdavfs"
PACKAGE_VERSION="0.2.3"

BUILT_MODULE_NAME[0]="kwebdavfs"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"

MAKE[0]="make KVER=${kernelver} KDIR=${kernel_source_dir}"
CLEAN="make KVER=${kernelver} KDIR=${kernel_source_dir} clean"
