#!/bin/bash
set -e

VERSION=$(dpkg-query --showformat='${Version}' --show kwebdavfs-dkms 2>/dev/null \
          | cut -d- -f1) || true

case "$1" in
    remove|upgrade|deconfigure)
        modprobe -r kwebdavfs 2>/dev/null || true
        if [ -n "$VERSION" ]; then
            dkms remove -m kwebdavfs -v "$VERSION" --all 2>/dev/null || true
        fi
        rm -f /etc/modules-load.d/kwebdavfs.conf
        ;;
    failed-upgrade)
        ;;
esac

exit 0
